### ISSUE TITLE
gpu util problem

### ISSUE THREAD

**Issue by db3ppp** [MaybeShewill-CV/attentive-gan-derainnet#50]
![캡처](https://user-images.githubusercontent.com/37920535/61631578-b2371580-acc5-11e9-9952-dcd911111112.JPG)

As shown above, gpu memory is allocated, but volatile GPU-util is 0%. I do not know why gpu is not used for learning.

**Comment by MaybeShewill-CV** [comment]
@db3ppp Check if your gpu tensorflow is successfully installed. Most of the problem was caused due to that:)
